# Generated by Django 5.0.6 on 2024-08-01 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Placed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(1)])),
                ('description', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)])),
                ('category', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(1)])),
            ],
        ),
    ]
