# Generated by Django 5.0.6 on 2024-08-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_placed_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placed',
            name='url',
            field=models.URLField(blank=True, default='No Photo'),
        ),
    ]
