# Generated by Django 5.0.6 on 2024-08-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_bids_id_alter_comments_id_alter_placed_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placed',
            name='url',
            field=models.ImageField(blank=True, default='No Image', upload_to='auctions\\static\x07uctions\\images'),
        ),
    ]
