# Generated by Django 5.0.6 on 2024-08-01 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_placed_description_alter_placed_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placed',
            name='description',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
