# Generated by Django 5.0.6 on 2024-08-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_placed_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wishlist',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
