# Generated by Django 5.0.6 on 2024-08-03 19:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_wishlist_remove_user_wishlist_user_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bidding',
            field=models.ManyToManyField(blank=True, related_name='bid', to=settings.AUTH_USER_MODEL),
        ),
    ]
