# Generated by Django 5.0.6 on 2024-08-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_bids_bidding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='bidding',
        ),
        migrations.AddField(
            model_name='bids',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bids',
            name='item',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='bids',
            field=models.ManyToManyField(blank=True, related_name='bid', to='auctions.bids'),
        ),
    ]
