# Generated by Django 5.0.6 on 2024-08-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_alter_bids_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
