# Generated by Django 5.0.6 on 2024-08-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_placed_current_bid_alter_bids_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placed',
            name='current_bid',
            field=models.FloatField(),
        ),
    ]
