# Generated by Django 5.0.6 on 2024-08-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_alter_placed_current_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='placed',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='winning_bids',
            field=models.ManyToManyField(blank=True, related_name='winning_bid', to='auctions.bids'),
        ),
    ]
