# Generated by Django 5.0.6 on 2024-08-31 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_placed_closed_user_winning_bids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='username',
            new_name='name',
        ),
    ]
