# Generated by Django 5.0.6 on 2024-09-02 20:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_comments_name_commentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='name_commentor',
            field=models.CharField(default='Unknown User', max_length=100, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
